# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app # avoid re building after python code change (TODO remove in prod ?)
      - ./certs:/app/certs:ro # mount in ReadOnly mode the SSL certificate for https
    ports:
      - "8000:8000"
      - "8443:8443" # HTTPS port
    environment:
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SAMESITE=${SAMESITE_DEV}
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # 80 for production container
    volumes:
      - ./frontend:/app  # Volumn to mount original files
      - /app/node_modules  # avoid deleting nodes dependencies
      - ./certs:/app/certs:ro # mount in ReadOnly mode the SSL certificate for https
    environment:
      - CHOKIDAR_USEPOLLING=true  # Aide à détecter les changements de fichiers
      - WDS_SOCKET_PORT=0  # Pour WebpackDevServer
      - REACT_APP_API_URL=${API_URL}  # for Axios calls
    depends_on:
      - backend
  
  
  db:
    image: postgres:13
    ports:
    - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  postgres_data: