# docker-compose.yml
version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user:password@db/dbname
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # 80 for production container
    volumes:
      - ./frontend:/app  # Volumn to mount original files
      - /app/node_modules  # avoid deleting nodes dependencies
    environment:
      - CHOKIDAR_USEPOLLING=true  # Aide à détecter les changements de fichiers
      - WDS_SOCKET_PORT=0  # Pour WebpackDevServer
    depends_on:
      - backend
  
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname

volumes:
  postgres_data: