# Generated by Django 3.2.25 on 2025-07-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ncbi_id', models.CharField(max_length=255)),
                ('chromosome', models.CharField(max_length=5)),
                ('organism', models.CharField(max_length=255)),
                ('start_idx', models.IntegerField()),
                ('end_idx', models.IntegerField()),
                ('strand', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='Rna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ncbi_id', models.CharField(max_length=255)),
                ('is_protein_coding', models.BooleanField()),
                ('start_idx', models.IntegerField()),
                ('end_idx', models.IntegerField()),
                ('cds_start', models.IntegerField()),
                ('cds_end', models.IntegerField()),
                ('length', models.IntegerField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rnas', to='gene_rna_prot.gene')),
            ],
            options={
                'db_table': 'rna',
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ncbi_id', models.CharField(max_length=255)),
                ('length', models.IntegerField()),
                ('sequence', models.TextField(max_length=5000)),
                ('rna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='gene_rna_prot.rna')),
            ],
            options={
                'db_table': 'protein',
            },
        ),
    ]
